trigger:
  - main  # Adjust to your main branch

variables:
  dockerRegistryServiceConnection: 'ilifesregistry'  # Set this in DevOps
  imageName: 'ilifes-store'
  acrName: 'ilifesregistry.azurecr.io'
  sshServiceConnection: 'ilifes-ssh-connection'  # Set SSH service connection in DevOps
  appDirectory: '/var/www/html'  # Adjust if needed
  containerName: 'ilifes_web'

stages:
  - stage: Build
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: Build
        displayName: 'Build and Push'
        pool:
          name: 'DO-Agent-Pool'  # Use your self-hosted agent pool
        steps:
          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: $(dockerRegistryServiceConnection)

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              repository: $(acrName)/$(imageName)
              dockerfile: dockerfile
              tags: latest

          - task: Docker@2
            displayName: 'Push Docker Image to ACR'
            inputs:
              command: push
              repository: $(acrName)/$(imageName)
              tags: latest

  - stage: Deploy
    displayName: 'Deploy Application'
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: 'Deploy on Remote Server'
        pool:
          name: 'DO-Agent-Pool'  # Use your self-hosted agent pool
        steps:
          - task: SSH@0
            displayName: 'Pull and Restart Docker Containers'
            inputs:
              sshEndpoint: $(sshServiceConnection)
              runOptions: 'commands'
              commands: |
                cd $(appDirectory)
                docker-compose down
                docker pull $(acrName)/$(imageName):latest
                docker-compose up -d
              readyTimeout: '20000'  # Adjust timeout if needed
