services:
  web:
    build: .
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
      - /etc/letsencrypt/live/ilifes.store:/etc/letsencrypt/live/ilifes.store
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '@Shova595Bhandari'
      MYSQL_DATABASE: "ilife"
            
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '@Shova595Bhandari'
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
