
version: '3.8'

services:
  web:
    image: ilifesregistry.azurecr.io/ilifes-store:latest  # Use the fully qualified image name
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '@Shova595Bhandari'
      MYSQL_DATABASE: "ilife"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: '@Shova595Bhandari'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '@Shova595Bhandari'
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
