
services:
  web:
    image: ilifesregistry.azurecr.io/ilifesregistry.azurecr.io/ilifes-store:latest  # Use the fully qualified image name
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ssl_certs:/etc/ssl
      - /etc/apache2/sites-available/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf:ro
    depends_on:
      - db
    command: >
      /bin/bash -c "a2enmod ssl && a2ensite default-ssl && apache2-foreground"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '@Shova595Bhandari'
      MYSQL_DATABASE: "ilife"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: '@Shova595Bhandari'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '@Shova595Bhandari'
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
  ssl_certs:
    external: true # Ensure this volume is created externally for SSL certificates
